from sqlalchemy import Column, BigInteger, Integer, String, Date, Time
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class TBL_RACCESOS_DOWNLOAD(Base):
    __tablename__ = 'TBL_RACCESOS_DOWNLOAD'
    ACC_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    ACC_CNOMBRE_ACCESO = Column(String, nullable=True)
    ACC_NAZU_NID = Column(BigInteger, nullable=True)
    ACC_CGRABADORA = Column(String(255), nullable=True)
    ACC_CROUTE_URL_GRAB = Column(String, nullable=True)
    ACC_CUSUARIO = Column(String(255), nullable=True)
    ACC_CPASSWORD = Column(String(255), nullable=True)
    ACC_CESTADO_REGISTRO = Column(String(255), nullable=True)
    ACC_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    ACC_DFECHA_REGISTRO = Column(Date, nullable=True)
    ACC_DHORA_REGISTRO = Column(Time, nullable=True)
    ACC_CCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    ACC_DFECHA_UPDATE = Column(Date, nullable=True)
    ACC_DHORA_UPDATE = Column(Time, nullable=True)
    ACC_CDETALLE1 = Column(String, nullable=True)
    ACC_CDETALLE2 = Column(String, nullable=True)
    ACC_CDETALLE3 = Column(String, nullable=True)
    ACC_CDETALLE4 = Column(String, nullable=True)
    ACC_CDETALLE5 = Column(String, nullable=True)

class TBL_RAZURE_CONFIGURATION(Base):
    __tablename__ = 'TBL_RAZURE_CONFIGURATION'
    AZU_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    AZU_CCOMPANY = Column(String, nullable=True)
    AZU_CCUSTOMER = Column(String, nullable=True)
    AZU_CSESSION = Column(String, nullable=True)
    AZU_CSUBSESSION = Column(String, nullable=True)
    AZU_CLANGUAGE = Column(String(255), nullable=True)
    AZU_NMAX_AUDIOS_MES = Column(BigInteger, nullable=True)
    AZU_CESTADO_REGISTRO = Column(String(255), nullable=True)
    AZU_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    AZU_DFECHA_REGISTRO = Column(Date, nullable=True)
    AZU_DHORA_REGISTRO = Column(Time, nullable=True)
    AZU_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    AZU_DFECHA_UPDATE = Column(Date, nullable=True)
    AZU_DHORA_UPDATE = Column(Time, nullable=True)
    AZU_CDETALLE1 = Column(String, nullable=True)
    AZU_CDETALLE2 = Column(String, nullable=True)
    AZU_CDETALLE3 = Column(String, nullable=True)
    AZU_CDETALLE4 = Column(String, nullable=True)
    AZU_CDETALLE5 = Column(String, nullable=True)

class TBL_RCLIENTS_CONFIG(Base):
    __tablename__ = 'TBL_RCLIENTS_CONFIG'
    CLI_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    CLI_CCLIENTE_NAME = Column(String, nullable=True)
    CLI_CESTADO_REGISTRO = Column(String(255), nullable=True)
    CLI_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    CLI_DFECHA_REGISTRO = Column(Date, nullable=True)
    CLI_DHORA_REGISTRO = Column(Time, nullable=True)
    CLI_CCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    CLI_DFECHA_UPDATE = Column(Date, nullable=True)
    CLI_DHORA_UPDATE = Column(Time, nullable=True)
    CLI_CDETALLE1 = Column(String, nullable=True)
    CLI_CDETALLE2 = Column(String, nullable=True)
    CLI_CDETALLE3 = Column(String, nullable=True)
    CLI_CDETALLE4 = Column(String, nullable=True)
    CLI_CDETALLE5 = Column(String, nullable=True)

class TBL_RCONNECT_CONFIGURATION(Base):
    __tablename__ = 'TBL_RCONNECT_CONFIGURATION'
    CON_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    CON_CNOMBRE_CONFIG = Column(String, nullable=True)
    CON_CTIPO_CONNECT = Column(String(255), nullable=True)
    CON_CSERVIDOR_CONNECT = Column(String(255), nullable=True)
    CON_CUSUARIO_CONNECT = Column(String(255), nullable=True)
    CON_CPASSWORD_CONNECT = Column(String(255), nullable=True)
    CON_CFOLDER_MAJOR = Column(String(255), nullable=True)
    CON_CPORT_CONNECT = Column(String(255), nullable=True)
    CON_CESTADO_REGISTRO = Column(String(255), nullable=True)
    CON_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    CON_DFECHA_REGISTRO = Column(Date, nullable=True)
    CON_DHORA_REGISTRO = Column(Time, nullable=True)
    CON_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    CON_DFECHA_UPDATE = Column(Date, nullable=True)
    CON_DHORA_UPDATE = Column(Time, nullable=True)
    CON_CDETALLE1 = Column(String, nullable=True)
    CON_CDETALLE2 = Column(String, nullable=True)
    CON_CDETALLE3 = Column(String, nullable=True)
    CON_CDETALLE4 = Column(String, nullable=True)
    CON_CDETALLE5 = Column(String, nullable=True)

class TBL_RCREDENCIAL_INSIGHTS(Base):
    __tablename__ = 'TBL_RCREDENCIAL_INSIGHTS'
    CRE_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    CRE_CUSUARIO_INSIGHTS = Column(String, nullable=True)
    CRE_CNOMBRE_COMPLETO = Column(String, nullable=True)
    CRE_CDOCUMENTO = Column(String, nullable=True)
    CRE_CCLIENTE = Column(String(255), nullable=True)
    CRE_COPERACION = Column(String(255), nullable=True)
    CRE_CCARGO = Column(String(255), nullable=True)
    CRE_CJEFE_INMEDIATO = Column(String, nullable=True)
    CRE_CPASSWORD_NEW = Column(String, nullable=True)
    CRE_CPASSWORD_OLD1 = Column(String, nullable=True)
    CRE_CPASSWORD_OLD2 = Column(String, nullable=True)
    CRE_CPASSWORD_OLD3 = Column(String, nullable=True)
    CRE_CESTADO_PASSWORD = Column(String(255), nullable=True)
    CRE_NINTENTOS_PASWORD = Column(Integer, nullable=True)
    CRE_DFECHA_PASS_UPD = Column(Date, nullable=True)
    CRE_DHORA_PASS_UPD = Column(Time, nullable=True)
    CRE_NACCESO = Column(BigInteger, nullable=True)
    CRE_CESTADO_REGISTRO = Column(String(255), nullable=True)
    CRE_DFECHA_REGISTRO = Column(Date, nullable=True)
    CRE_DHORA_REGISTRO = Column(Time, nullable=True)
    CRE_DFECHA_UPDATE = Column(Date, nullable=True)
    CRE_DHORA_UPDATE = Column(Time, nullable=True)
    CRE_CCOMMAND_INSIGHTS = Column(String, nullable=True)
    CRE_CDETALLE1 = Column(String, nullable=True)
    CRE_CDETALLE2 = Column(String, nullable=True)
    CRE_CDETALLE3 = Column(String, nullable=True)
    CRE_CDETALLE4 = Column(String, nullable=True)
    CRE_CDETALLE5 = Column(String, nullable=True)

class TBL_RFILTER_CONFIG_INFORMATION(Base):
    __tablename__ = 'TBL_RFILTER_CONFIG_INFORMATION'
    FIL_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    FIL_CNOMBRE_CONFIG = Column(String, nullable=True)
    FIL_CTYPE_CONFIG = Column(String(255), nullable=True)
    FIL_CSERVER_CONFIG = Column(String(255), nullable=True)
    FIL_CDATABASE_CONFIG = Column(String(255), nullable=True)
    FIL_CUSERNAME_CONFIG = Column(String(255), nullable=True)
    FIL_CPASSWORD_CONFIG = Column(String(255), nullable=True)
    FIL_CPORT_CONFIG = Column(String(255), nullable=True)
    FIL_CESTADO_REGISTRO = Column(String(255), nullable=True)
    FIL_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    FIL_DFECHA_REGISTRO = Column(Date, nullable=True)
    FIL_DHORA_REGISTRO = Column(Time, nullable=True)
    FIL_CCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    FIL_DFECHA_UPDATE = Column(Date, nullable=True)
    FIL_DHORA_UPDATE = Column(Time, nullable=True)
    FIL_CDETALLE1 = Column(String, nullable=True)
    FIL_CDETALLE2 = Column(String, nullable=True)
    FIL_CDETALLE3 = Column(String, nullable=True)
    FIL_CDETALLE4 = Column(String, nullable=True)
    FIL_CDETALLE5 = Column(String, nullable=True)

class TBL_RMODULE_INSIGHTS(Base):
    __tablename__ = 'TBL_RMODULE_INSIGHTS'
    MOD_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    MOD_CMODULE_NAME = Column(String, nullable=True)
    MOD_CSUBMODULE_NAME = Column(String, nullable=True)
    MOD_CKEY_MODULE = Column(String(255), nullable=True)
    MOD_CESTADO_REGISTRO = Column(String(255), nullable=True)
    MOD_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    MOD_DFECHA_REGISTRO = Column(Date, nullable=True)
    MOD_DHORA_REGISTRO = Column(Time, nullable=True)
    MOD_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    MOD_DFECHA_UPDATE = Column(Date, nullable=True)
    MOD_DHORA_UPDATE = Column(Time, nullable=True)

class TBL_TDOWNLOAD_PROCESS(Base):
    __tablename__ = 'TBL_TDOWNLOAD_PROCESS'
    DOW_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    DOW_NAZU_NID = Column(BigInteger, nullable=True)
    DOW_CGRABADORA = Column(String(255), nullable=True)
    DOW_NACC_NID = Column(BigInteger, nullable=True)
    DOW_CDETALLE_DOWNLOAD1 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD2 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD3 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD4 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD5 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD6 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD7 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD8 = Column(String, nullable=True)
    DOW_CDETALLE_DOWNLOAD9 = Column(String, nullable=True)
    DOW_CTIPO_CANTIDAD = Column(String(255), nullable=True)
    DOW_NCANTIDAD_AUDIOS = Column(Integer, nullable=True)
    DOW_CESTADO_PROCESO = Column(String(255), nullable=True)
    DOW_CESTADO_REGISTRO = Column(String(255), nullable=True)
    DOW_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    DOW_DFECHA_REGISTRO = Column(Date, nullable=True)
    DOW_DHORA_REGISTRO = Column(Time, nullable=True)
    DOW_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    DOW_DFECHA_UPDATE = Column(Date, nullable=True)
    DOW_DHORA_UPDATE = Column(Time, nullable=True)
    DOW_CDETALLE1 = Column(String, nullable=True)
    DOW_CDETALLE2 = Column(String, nullable=True)
    DOW_CDETALLE3 = Column(String, nullable=True)
    DOW_CDETALLE4 = Column(String, nullable=True)
    DOW_CDETALLE5 = Column(String, nullable=True)

class TBL_TMANAGE_INSIGHTS(Base):
    __tablename__ = 'TBL_TMANAGE_INSIGHTS'
    MAN_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    MAN_NCRE_NID = Column(BigInteger, nullable=True)
    MAN_NMOD_NID = Column(BigInteger, nullable=True)
    MAN_CTYPE_PERMISO = Column(String(255), nullable=True)
    MAN_CESTADO_REGISTRO = Column(String(255), nullable=True)
    MAN_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    MAN_DFECHA_REGISTRO = Column(Date, nullable=True)
    MAN_DHORA_REGISTRO = Column(Time, nullable=True)
    MAN_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    MAN_DFECHA_UPDATE = Column(Date, nullable=True)
    MAN_DHORA_UPDATE = Column(Time, nullable=True)

class TBL_TPERMISOS_INSIGHTS(Base):
    __tablename__ = 'TBL_TPERMISOS_INSIGHTS'
    PER_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    PER_NCRE_NID = Column(BigInteger, nullable=True)
    PER_CAZU_CCOMPANY = Column(String, nullable=True)
    PER_CAZU_CCUSTOMER = Column(String, nullable=True)
    PER_CESTADO_REGISTRO = Column(String(255), nullable=True)
    PER_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    PER_DFECHA_REGISTRO = Column(Date, nullable=True)
    PER_DHORA_REGISTRO = Column(Time, nullable=True)
    PER_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    PER_DFECHA_UPDATE = Column(Date, nullable=True)
    PER_DHORA_UPDATE = Column(Time, nullable=True)

class TBL_TINSIGHTS_PROCESS(Base):
    __tablename__ = 'TBL_TINSIGHTS_PROCESS'
    INS_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    INS_CNAME_INSIGHTS = Column(String, nullable=True)
    INS_CPAIS_INSIGHTS = Column(String(255), nullable=True)
    INS_NCLI_NID = Column(BigInteger, nullable=True)
    INS_NCON_NID = Column(BigInteger, nullable=True)
    INS_CROUTE_ADD_LIST = Column(String, nullable=True)
    INS_CTYPE_ROUTE_LIST = Column(String(255), nullable=True)
    INS_CTYPE_DATE_CONFIG = Column(String(255), nullable=True)
    INS_NAZU_NID = Column(BigInteger, nullable=True)
    INS_NMAX_AUDIOS_DAY = Column(BigInteger, nullable=True)
    INS_NFIL_NID = Column(BigInteger, nullable=True)
    INS_CMTDT_FILTER_VALOR_ONE = Column(String, nullable=True)
    INS_CMTDT_FILTER_VALOR_TWO = Column(String, nullable=True)
    INS_CMTDT_FILTER_VALOR_THREE = Column(String, nullable=True)
    INS_CCOLUMNS_MTDT_RETURN = Column(String, nullable=True)
    INS_CESTADO_PROCESO = Column(String(255), nullable=True)
    INS_CESTADO_REGISTRO = Column(String(255), nullable=True)
    INS_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    INS_DFECHA_REGISTRO = Column(Date, nullable=True)
    INS_DHORA_REGISTRO = Column(Time, nullable=True)
    INS_NCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    INS_DFECHA_UPDATE = Column(Date, nullable=True)
    INS_DHORA_UPDATE = Column(Time, nullable=True)
    INS_CDETALLE1 = Column(String, nullable=True)
    INS_CDETALLE2 = Column(String, nullable=True)
    INS_CDETALLE3 = Column(String, nullable=True)
    INS_CDETALLE4 = Column(String, nullable=True)
    INS_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_1(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_1'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_2(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_2'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_3(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_3'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_4(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_4'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_5(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_5'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_6(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_6'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_7(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_7'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_8(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_8'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_9(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_9'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_10(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_10'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_11(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_11'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_LLOG_INSIGHTS_PROCESS_12(Base):
    __tablename__ = 'TBL_LLOG_INSIGHTS_PROCESS_12'
    LOG_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    LOG_NINS_NID = Column(BigInteger, nullable=True)
    LOG_DFECHA_PROCESO = Column(Date, nullable=True)
    LOG_DFECHA_INICIO = Column(Date, nullable=True)
    LOG_DHORA_INICIO = Column(Time, nullable=True)
    LOG_NAUDIOS_PROCESAR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_CONVERTIR = Column(BigInteger, nullable=True)
    LOG_NAUDIOS_AZURE = Column(BigInteger, nullable=True)
    LOG_DFECHA_FIN = Column(Date, nullable=True)
    LOG_DHORA_FIN = Column(Time, nullable=True)
    LOG_CESTADO_REGISTRO = Column(String(255), nullable=True)
    LOG_CDETALLE1 = Column(String, nullable=True)
    LOG_CDETALLE2 = Column(String, nullable=True)
    LOG_CDETALLE3 = Column(String, nullable=True)
    LOG_CDETALLE4 = Column(String, nullable=True)
    LOG_CDETALLE5 = Column(String, nullable=True)

class TBL_TDATE_INSIGHTS_PROCESS(Base):
    __tablename__ = 'TBL_TDATE_INSIGHTS_PROCESS'
    DAT_NID = Column(BigInteger, primary_key=True, autoincrement=True)
    DAT_NINS_NID = Column(BigInteger, nullable=True)
    DAT_DFECHA_PROCESO = Column(Date, nullable=True)
    DAT_CESTADO_REGISTRO = Column(String(255), nullable=True)
    DAT_NCRE_NID_REGISTRO = Column(BigInteger, nullable=True)
    DAT_DFECHA_REGISTRO = Column(Date, nullable=True)
    DAT_DHORA_REGISTRO = Column(Time, nullable=True)
    DAT_CCRE_NID_UPDATE = Column(BigInteger, nullable=True)
    DAT_DFECHA_UPDATE = Column(Date, nullable=True)
    DAT_DHORA_UPDATE = Column(Time, nullable=True)

